package Telas;

import Conexao.Usuario;
import Conexao.UsuarioDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class ViewCadastro extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastro
     */
    public ViewCadastro() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/tartaruga1.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNomeField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jUsuarioField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jEmailField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSenhaField4 = new javax.swing.JPasswordField()
        ;
        jLabel8 = new javax.swing.JLabel();
        jCpfField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jIdadeField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSexoBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastre-se");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(98, 163, 219));
        jLabel2.setText("Cadastro");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(98, 163, 219));
        jLabel3.setText("\"Uma Vida Sustentável\"");

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(98, 163, 219));
        jLabel4.setText("Nome:");

        jNomeField1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jNomeField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jNomeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(98, 163, 219));
        jLabel5.setText("Login:");
        jLabel5.setToolTipText("");

        jUsuarioField2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jUsuarioField2.setToolTipText("Login com o que voce iniciara sessão");
        jUsuarioField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jUsuarioField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuarioField2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(98, 163, 219));
        jLabel6.setText("E-mail:");

        jEmailField3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jEmailField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jEmailField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(98, 163, 219));
        jLabel7.setText("Senha:");

        jSenhaField4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jSenhaField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jSenhaField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSenhaField4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(98, 163, 219));
        jLabel8.setText("CPF:");

        jCpfField5.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jCpfField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jCpfField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCpfField5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(98, 163, 219));
        jLabel9.setText("Já é registrado?");

        jIdadeField6.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jIdadeField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jIdadeField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdadeField6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(98, 163, 219));
        jLabel11.setText("Idade:");

        jSexoBox1.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jSexoBox1.setForeground(new java.awt.Color(98, 163, 219));
        jSexoBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        jSexoBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jSexoBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSexoBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(98, 163, 219));
        jLabel10.setText("Sexo:");

        jButton1.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(98, 163, 219));
        jButton1.setText("Feito!");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 38, 255));
        jButton2.setText("Entre aqui!");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jUsuarioField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jEmailField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCpfField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jIdadeField6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSexoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addComponent(jSenhaField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCpfField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsuarioField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIdadeField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmailField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSexoBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSenhaField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       ViewLogin lgf = new ViewLogin();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jCpfField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCpfField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCpfField5ActionPerformed

    private void jSexoBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSexoBox1ActionPerformed

    private void jNomeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        var novoLogin = jUsuarioField2.getText();
        var novaSenha = jSenhaField4.getText();
        var novoNome = jNomeField1.getText();
        var novoCPF = jCpfField5.getText();
        var novoEmail = jEmailField3.getText();
        var novaIdade = jIdadeField6.getText();
        var novoSexo = jSexoBox1.getSelectedItem();
        //string pool
        if (!novaSenha.trim().isEmpty() && !novoLogin.trim().isEmpty() && !novoNome.trim().isEmpty() && !novoCPF.trim().isEmpty() && !novoEmail.trim().isEmpty() && !novaIdade.trim().isEmpty() && novoSexo != null){
            var usuario = new Usuario(novoLogin, novaSenha, novoNome, novoCPF, novoEmail, novaIdade, novoSexo);
            var dao = new UsuarioDAO();
            try {
                dao.cadastrar(usuario);
                if(dao.existe(usuario)){
                    JOptionPane.showMessageDialog(null, "Usuario Cadastrado");
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possivel realizar o cadastro");
                }
                
            } catch (Exception ex) {
                Logger.getLogger(ViewCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jUsuarioField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuarioField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsuarioField2ActionPerformed

    private void jSenhaField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSenhaField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSenhaField4ActionPerformed

    private void jEmailField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailField3ActionPerformed

    private void jIdadeField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdadeField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdadeField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCpfField5;
    private javax.swing.JTextField jEmailField3;
    private javax.swing.JTextField jIdadeField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSenhaField4;
    private javax.swing.JComboBox<String> jSexoBox1;
    private javax.swing.JTextField jUsuarioField2;
    // End of variables declaration//GEN-END:variables
}
