package Telas;

import Conexao.Usuario;
import Conexao.UsuarioDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cliente
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
    }

 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        umaVidaSustentavel = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        jbAvancar = new javax.swing.JButton();
        naotemumaconta = new javax.swing.JLabel();
        jbCrieAqui = new javax.swing.JButton();
        mostrarSenha = new javax.swing.JCheckBox();
        pword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        login.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        login.setForeground(new java.awt.Color(98, 163, 219));
        login.setText("Login");

        umaVidaSustentavel.setFont(new java.awt.Font("Calisto MT", 2, 18)); // NOI18N
        umaVidaSustentavel.setForeground(new java.awt.Color(98, 163, 219));
        umaVidaSustentavel.setText("\"Uma Vida Sustentável\"");

        usuario.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        usuario.setForeground(new java.awt.Color(98, 163, 219));
        usuario.setText("Usuário:");

        txtUsuario.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        senha.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        senha.setForeground(new java.awt.Color(98, 163, 219));
        senha.setText("Senha:");

        jbAvancar.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        jbAvancar.setForeground(new java.awt.Color(98, 163, 219));
        jbAvancar.setText("Avançar");
        jbAvancar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));
        jbAvancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAvancarActionPerformed(evt);
            }
        });

        naotemumaconta.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        naotemumaconta.setForeground(new java.awt.Color(98, 163, 219));
        naotemumaconta.setText("Não tem uma conta?");

        jbCrieAqui.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jbCrieAqui.setForeground(new java.awt.Color(0, 38, 255));
        jbCrieAqui.setText("Crie aqui!");
        jbCrieAqui.setBorder(null);
        jbCrieAqui.setContentAreaFilled(false);
        jbCrieAqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCrieAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCrieAquiMouseClicked(evt);
            }
        });
        jbCrieAqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrieAquiActionPerformed(evt);
            }
        });

        mostrarSenha.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        mostrarSenha.setForeground(new java.awt.Color(98, 163, 219));
        mostrarSenha.setText("Mostrar senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });

        pword.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        pword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(98, 163, 219), 2, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(login))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(umaVidaSustentavel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario)
                            .addComponent(senha)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrarSenha)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jbAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(naotemumaconta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCrieAqui)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umaVidaSustentavel)
                .addGap(46, 46, 46)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAvancar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naotemumaconta)
                    .addComponent(jbCrieAqui))
                .addGap(20, 20, 20))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        if(mostrarSenha.isSelected()){
            pword.setEchoChar((char)0);
        }
        else{
            pword.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void jbCrieAquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrieAquiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCrieAquiActionPerformed

    private void jbCrieAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCrieAquiMouseClicked
        ViewCadastro rgf = new ViewCadastro();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jbCrieAquiMouseClicked

    private void jbAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAvancarActionPerformed
    try{
            String login = txtUsuario.getText();
            String senha = new String(pword.getPassword());
            var usuario = new Usuario(login, senha);
            var dao = new UsuarioDAO();
            if(dao.existe(usuario)){
                if(usuario.getTipo()== 1){
                    JOptionPane.showMessageDialog(null, "Bem vindo " + login + "!");
                    ViewTelaAdmin vta = new ViewTelaAdmin();
                    vta.setVisible(true);
                    vta.pack();
                    vta.setLocationRelativeTo(null);
                    vta.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Bem vindo " + login + "!");
                    ViewTelaComum vtc = new ViewTelaComum();
                    vtc.setVisible(true);
                    vtc.pack();
                    vtc.setLocationRelativeTo(null);
                    vtc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválido");
                
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro no sistema. Tente novamente mais tarde");
        }
    }//GEN-LAST:event_jbAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbAvancar;
    private javax.swing.JButton jbCrieAqui;
    private javax.swing.JLabel login;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JLabel naotemumaconta;
    private javax.swing.JPasswordField pword;
    private javax.swing.JLabel senha;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel umaVidaSustentavel;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
